### ISSUE TITLE
Добавить игрушку арирал

### ISSUE THREAD

**Issue by YaraYT** [Cybersun-Industries/ServerBuild#138]
## 1. Тема предложения (название):

**Игрушка Арирала "Игрушечная Аргемия"**

## 2. Основная информация про предлагаемое:

* **Размер:** 1 тайтл
* **Расположение:** 
    * Может быть найдена в техах
    * Доступна для заказа за 500 кредитов
* **Функции:**
    * Нельзя поднять
    * Можно таскать
    * При нажатии или ударе об стену издает звуки (писк или звуки феленидов)
* **Имя:** Игрушечная Аргемия (Игрушечный арирал)
* **Описание:** "Чёртов пранкер"
* **Спрайт:** (спрайт необходимо предоставить в отдельной ветке)

## 3. Зачем это нужно:

* Добавляет в игру новый интересный предмет, который можно использовать для веселья и розыгрышей.
* Увеличивает разнообразие предметов в игре.
* Позволяет игрокам иметь маленького арирала у себя дома.
* Может быть использована как декор для базы.
* Дает игрокам возможность получить звуки феленидов без необходимости иметь в своем питомце арирала.
![Argemsmolspin](https://github.com/Cybersun-Industries/ServerBuild/assets/100045329/ff5aad14-54c4-40d4-a56f-48487a1faad1)

**Comment by YaraYT** [comment]
[твоюже мать это арирал!.zip](https://github.com/Cybersun-Industries/ServerBuild/files/15017447/default.zip)
Спрайти!

**Comment by Ilysha998** [comment]
не поверишь, но я ее пепвым делом и добавил
