### ISSUE TITLE
Автоматическая активация отряда Эподрона Смерти NanoTrasen при смерти ОЦК на космической станции

### ISSUE THREAD

**Issue by YaraYT** [Cybersun-Industries/ServerBuild#144]
### Описание

**1. Тема предложения (название):** Автоматическая активация отряда Эподрона Смерти NanoTrasen при смерти ОЦК на космической станции

**2. Основная информация про предлагаемое:**

При смерти ОЦК на **космической станции NanoTrasen**, если он находится на борту, автоматически разрываются все активные контракты и на станцию десантируется отряд Эподрона Смерти NanoTrasen.

**3. Зачем это нужно:**

- Повышение реалистичности и атмосферы игры, соответствующей деятельности корпорации NanoTrasen в космическом пространстве.
- Создание дополнительных сложностей и задач для игроков, стимулируя слаженную работу и защиту ОЦК.
- Введение элемента неожиданности и динамизма в игровой процесс.

**4. Дополнительная информация:**

- Эскадрон Смерти NanoTrasen - это элитный отряд высококвалифицированных бойцов, специально обученных для выполнения опасных миссий в космических условиях.
- Их основная задача - зачистить станцию от враждебных элементов и эвакуировать тело ОЦК.(Враждебные элементы-это вся станция....)
- Эксадрон Смерти оснащены самым современным оружием и защитными костюмами, соответствующими космическим стандартам NanoTrasen.

**5. Пример реализации:**

- При регистрации смерти ОЦК на его КПК поступает сообщение с информацией о его гибели и активации протокола защиты.
- Через 15 секунд после фиксации смерти ОЦК на станцию десантируется отряд Эподрона Смерти NanoTrasen.
- Эксадрон Смерти, действуя согласно протоколу, должны зачистить станцию от любых угроз, потенциально препятствующих эвакуации тела ОЦК.
- После выполнения задачи Эподраны Смерти эвакуируют тело ОЦК со станции, следуя дальнейшим инструкциям командования NanoTrasen.

**Comment by Ilysha998** [comment]
в дсе разобрали уже, что фигня полная
